apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: my-location-consumer
  name: my-location-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: my-location-consumer
  template:
    metadata:
      labels:
        service: my-location-consumer
    spec:
      containers:
      - image: chrisking99/mylocationconsumer:latest
        name: my-location-consumer
        imagePullPolicy: Always
        env:
        - name: KAFKA_BS_NAME
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_BS_NAME
        - name: KAFKA_BS_PORT
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_BS_PORT
        - name: KAFKA_BROKER_LIST_NAME
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_BROKER_LIST_NAME    
        - name: KAFKA_BROKER_PORT
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_BROKER_PORT
        - name: CREATE_PERSON_TOPIC
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: CREATE_PERSON_TOPIC
        - name: CREATE_LOCATION_TOPIC
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: CREATE_LOCATION_TOPIC
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
