apiVersion: v1
kind: Service
metadata:
  labels:
    service: my-udaconnect-app
  name: my-udaconnect-app
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
    nodePort: 30008
  selector:
    service: my-udaconnect-app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: my-udaconnect-app
  name: my-udaconnect-app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: my-udaconnect-app
  template:
    metadata:
      labels:
        service: my-udaconnect-app
    spec:
      containers:
      - image: chrisking99/myudaconnectapp:latest
        name: my-udaconnect-app
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "64m"
          limits:
            memory: "256Mi"
            cpu: "256m"
      restartPolicy: Always
