apiVersion: v1
kind: Service
metadata:
  labels:
    service: my-connection-api
  name: my-connection-api
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30007
  selector:
    service: my-connection-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: my-connection-api
  name: my-connection-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: my-connection-api
  template:
    metadata:
      labels:
        service: my-connection-api
    spec:
      containers:
      - image: chrisking99/myapiconnection:latest
        name: my-connection-api
        imagePullPolicy: Always
        env:
        - name: PERSONS_API
          valueFrom:
            configMapKeyRef:
              name: svc-reg
              key: PERSONS_API
        - name: PERSONS_API_PORT
          valueFrom:
            configMapKeyRef:
              name: svc-reg
              key: PERSONS_API_PORT
        - name: KAFKA_BS_NAME
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_BS_NAME
        - name: KAFKA_BS_PORT
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_BS_PORT
        - name: KAFKA_BROKER_LIST_NAME
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_BROKER_LIST_NAME    
        - name: KAFKA_BROKER_PORT
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_BROKER_PORT
        - name: CREATE_PERSON_TOPIC
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: CREATE_PERSON_TOPIC
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
